### ISSUE TITLE
react子应用提示跨域了

### ISSUE THREAD

**Issue by qd256wd** [DJYang666/qiankun#1]
react设置了 "Access-Control-Allow-Origin": '*'，为什么主应用访问子应用还是提示跨域了，vue项目按照示例是没有问题的，可以访问

**Comment by DJYang666** [comment]
能截图看看react的config文件吗

**Comment by qd256wd** [comment]
> 能截图看看react的config文件吗

![045f279cde4cbec1e8aa91fdf93b9a5](https://user-images.githubusercontent.com/50793173/105462183-3a3a1900-5cc9-11eb-8332-0bdb9f5bbddb.png)
///////////////react的
webpack: (config) => {
        config.output.library = 'reactApp';
        config.output.libraryTarget = 'umd';
        config.output.publicPath = 'http://localhost:20000/';
        return config;
    },
    devServer: (configFunction) => {
        return function(proxy, allowedHost) {
            const config = configFunction(proxy, allowedHost);
            config.headers = {
                "Access-Control-Allow-Origin": '*'
            }
            return config
        }
    }

**Comment by DJYang666** [comment]
我这边网络有延迟，还是直接贴代码端吧，直接拷贝上来看看

**Comment by DJYang666** [comment]
如果是照着例子来的话应该是没问题的，你是直接把项目拉下来跑吗？

**Comment by qd256wd** [comment]
> 我这边网络有延迟，还是直接贴代码端吧，直接拷贝上来看看
//qiankun-base 的main.js的配置，我配20000端口的话，不会报跨域，也没有效果，配3000端口的话，跨域了
registerMicroApps([{
        name: 'vueApp', // 应用的名字
        entry: '//localhost:10000', // 默认会加载这个html 解析里面的js 动态的执行 （子应用必须支持跨域）fetch
        container: '#vue', // 容器名
        activeRule: '/vue', // 激活的路径
    },
    {
        name: 'reactApp',
        entry: '//localhost:3000',
        container: '#react',
        activeRule: '/react',
    },
]);

**Comment by qd256wd** [comment]
> 如果是照着例子来的话应该是没问题的，你是直接把项目拉下来跑吗？

按照例子的话，我这边安装依赖一直装不上，就按照你  https://blog.csdn.net/qq_37947438/article/details/107666817    csdn上面的文章来的，用
cnpm install -g create-react-app
create-react-app my-app   命令创建的

**Comment by DJYang666** [comment]
嗯，主项目的entry配置是要和子项目的地址保持一致的，主项目配的是3000端口，react子项目端口是多少

**Comment by qd256wd** [comment]
> 嗯，主项目的entry配置是要和子项目的地址保持一致的，主项目配的是3000端口，react子项目端口是多少

子项目虽然通过config.output.publicPath = 'http://localhost:20000/';设置的是20000端口，但是用npm start跑起来，还是3000端口，是和跑起来的项目端口是一致的

**Comment by qd256wd** [comment]
> > 嗯，主项目的entry配置是要和子项目的地址保持一致的，主项目配的是3000端口，react子项目端口是多少
> 
> 子项目虽然通过config.output.publicPath =' [http：// localhost：20000 /';设置的是20000端口，但是用npm](http://localhost:20000/';%E8%AE%BE%E7%BD%AE%E7%9A%84%E6%98%AF20000%E7%AB%AF%E5%8F%A3%EF%BC%8C%E4%BD%86%E6%98%AF%E7%94%A8npm) start跑起来，还是3000端口，是和跑起来的项目端口是一致的

这边的vue子项目是没问题的设置的10000端口，跑起来也是10000端口

**Comment by DJYang666** [comment]
子项目最好还是改一下，改成3000端口，怕和本地端口有冲突，改完后重启项目一遍

**Comment by qd256wd** [comment]
> 子项目最好还是改一下，改成3000端口，怕和本地端口有冲突，改完后重启项目一遍

好，我试一下

**Comment by qd256wd** [comment]
> > 子项目最好还是改一下，改成3000端口，怕和本地端口有冲突，改完后重启项目一遍
> 
> 好，我试一下

刚刚把你的github上面的项目拉下来又跑了一遍，react项目里面的config.output.publicPath = 'http://localhost:3000/';好像只能设置为3000，设置为20000的话，报错找不到20000端口的一个js，
这边用npm start命令跑的话好像只能开3000端口，然后主应用相应的改成3000就行了

**Comment by DJYang666** [comment]
嗯，这就奇怪了，我有空看看什么问题，现在能运行起来就OK

**Comment by qd256wd** [comment]
> 嗯，这就奇怪了，我有空看看什么问题，现在能运行起来就OK
好，谢谢大佬，嘿嘿
